const SUPABASE_URL='https://ipnbebwrefxlvoqneaga.supabase.co';
const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwbmJlYndyZWZ4bHZvcW5lYWdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg4ODExOTUsImV4cCI6MjEwNDQ1NzE5NX0.1xMB8DbV__RK8D4PkuYANPARr2IkR_Rsyakh3sU8AAU';
const supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{flowType:'pkce',detectSessionInUrl:true,persistSession:true,autoRefreshToken:true}});
const $=s=>document.querySelector(s);let session=null,guest=false,mode='chat',currentChatId=null,chatMessages=[],playingAudio=null;let historyRequest=0,saveTimer=null,saveInFlight=false,saveQueued=false;
const MAX_INPUT=4000,MAX_MESSAGES=100,MAX_HISTORY=12;
const messages=$('#messages'),welcome=$('#welcome'),input=$('#prompt'),send=$('#send'),historyList=$('.history');
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),3200)}
function addMessage(role,text){welcome.style.display='none';const row=document.createElement('div');row.className=`message ${role}`;const av=document.createElement('div');av.className='avatar';av.textContent=role==='ai'?'M':'You';const bubble=document.createElement('div');bubble.className='bubble';bubble.textContent=text;if(role==='ai'){const wrap=document.createElement('div');wrap.className='ai-content';wrap.appendChild(bubble);const speak=document.createElement('button');speak.className='speak-btn';speak.title='Read aloud';speak.setAttribute('aria-label','Read aloud');speak.textContent='🔊';speak.onclick=()=>speakText(text,speak);wrap.appendChild(speak);row.append(av,wrap)}else row.append(bubble,av);messages.appendChild(row);messages.parentElement.scrollTop=messages.parentElement.scrollHeight;return bubble}
function sanitizeMessages(items){if(!Array.isArray(items))return [];return items.slice(-MAX_MESSAGES).filter(m=>m&&((m.role==='user')||(m.role==='ai'))&&typeof m.text==='string').map(m=>({role:m.role,text:m.text.slice(0,MAX_INPUT)}))}
function renderMessages(items){const safe=sanitizeMessages(items);messages.innerHTML='';welcome.style.display=safe.length?'none':'block';safe.forEach(m=>addMessage(m.role,m.text))}
function setUserUI(){const name=session?.user?.user_metadata?.full_name||session?.user?.email?.split('@')[0]||'Guest';$('#userName').textContent=name;$('#userPlan').textContent=guest?'Guest access':session?'Cloud sync enabled':'Sign in to sync';$('#userAvatar').textContent=name.slice(0,1).toUpperCase();$('#authBtn').textContent=guest||session?'Sign out':'Sign in'}
async function loadSession(){const {data}=await supabase.auth.getSession();if(data.session!==session?.id){session=data.session;guest=!session&&localStorage.getItem('munna_guest_mode')==='1';setUserUI();if(session){localStorage.removeItem('munna_guest_mode');await loadHistory()}}}
function authHeaders(){if(session?.access_token)return {'Authorization':`Bearer ${session.access_token}`,'Content-Type':'application/json'};let id=localStorage.getItem('munna_guest_id');if(!id){id=crypto.randomUUID();localStorage.setItem('munna_guest_id',id)}return {'X-Guest-Access':'true','X-Guest-Id':id,'Content-Type':'application/json'}}
function requireAccess(){if(!session&&!guest){$('#authModal').classList.add('open');return false}return true}
async function signIn(){const email=$('#email').value.trim(),password=$('#password').value;if(!email||!password)return toast('Email aur password enter karo.');const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)return toast('Sign in failed. Email/password check karo.');session=data.session;guest=false;localStorage.removeItem('munna_guest_mode');setUserUI();$('#authModal').classList.remove('open');await loadHistory();toast('Welcome back to Munna AI.')}
async function signUp(){const email=$('#email').value.trim(),password=$('#password').value;if(!email||password.length<6)return toast('Valid email aur 6+ character password chahiye.');const {data,error}=await supabase.auth.signUp({email,password});if(error)return toast(error.message);if(data.session){session=data.session;guest=false;setUserUI();$('#authModal').classList.remove('open');await loadHistory();toast('Account ready.')}else toast('Verification email check karo.')}
async function google(){const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin}});if(error)toast('Google sign in start nahi ho paaya.')}
async function logout(){await supabase.auth.signOut();session=null;guest=false;currentChatId=null;chatMessages=[];localStorage.removeItem('munna_guest_mode');setUserUI();renderMessages([]);renderHistory([]);toast('Signed out.')}
function guestLogin(){localStorage.setItem('munna_guest_mode','1');let id=localStorage.getItem('munna_guest_id');if(!id){id=crypto.randomUUID();localStorage.setItem('munna_guest_id',id)}guest=true;session=null;currentChatId=null;chatMessages=[];setUserUI();renderMessages([]);$('#authModal').classList.remove('open');toast('Guest mode enabled.')}
function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveChat(),500)}
async function saveChat(){if(!session||!chatMessages.length)return;if(saveInFlight){saveQueued=true;return}saveInFlight=true;saveQueued=false;const userId=session.user.id;const id=currentChatId||crypto.randomUUID();currentChatId=id;const title=(chatMessages.find(m=>m.role==='user')?.text||'New conversation').slice(0,70);const payload={id,user_id:userId,title,messages:sanitizeMessages(chatMessages),updated_at:new Date().toISOString()};try{const {error}=await supabase.from('chat_sessions').upsert(payload);if(error)console.warn('Chat sync failed:',error.message);else await loadHistory(false)}finally{saveInFlight=false;if(saveQueued)saveChat()}}
async function loadHistory(selectLatest=false){const request=++historyRequest;const userId=session?.user?.id;if(!userId){renderHistory([]);return}const {data,error}=await supabase.from('chat_sessions').select('id,title,messages,updated_at').order('updated_at',{ascending:false}).limit(30);if(request!==historyRequest||userId!==session?.user?.id)return;if(error){console.warn('History load failed:',error.message);return}const clean=(data||[]).filter(x=>x&&typeof x.id==='string').map(x=>({...x,messages:sanitizeMessages(x.messages)}));renderHistory(clean);if(selectLatest&&clean[0])openChat(clean[0])}
function renderHistory(items){historyList.innerHTML='';if(!items.length){const b=document.createElement('button');b.className='history-item active';b.textContent='✨ Welcome to Munna';historyList.appendChild(b);return}items.forEach(item=>{const b=document.createElement('button');b.className='history-item';b.textContent=item.title||'Untitled conversation';b.title=item.title||'';b.dataset.chatId=item.id;b.onclick=()=>openChat(item);historyList.appendChild(b)})}
function openChat(item){currentChatId=item.id;chatMessages=sanitizeMessages(item.messages);renderMessages(chatMessages);document.querySelectorAll('.history-item').forEach(b=>b.classList.toggle('active',b.dataset.chatId===item.id));input.focus()}
async function sendChat(){let text=input.value.trim();if(!text||!requireAccess())return;if(text.length>MAX_INPUT){toast(`Message ${MAX_INPUT} characters se zyada nahi ho sakta.`);return}input.value='';input.style.height='auto';send.disabled=true;if(!currentChatId)currentChatId=crypto.randomUUID();chatMessages=sanitizeMessages(chatMessages);chatMessages.push({role:'user',text});addMessage('user',text);const bubble=addMessage('ai','Munna soch raha hai…');try{const history=chatMessages.slice(-MAX_HISTORY).map(m=>({role:m.role==='user'?'user':'model',parts:[{text:m.text}]}));const res=await fetch('/api/chat',{method:'POST',headers:authHeaders(),body:JSON.stringify({payload:{contents:history},sse:false})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error('AI request failed');const answer=data?.candidates?.[0]?.content?.parts?.map(p=>typeof p.text==='string'?p.text:'').join('')||'Mujhe response nahi mila.';bubble.textContent=answer;const row=bubble.closest('.message');const old=row?.querySelector('.speak-btn');if(old)old.onclick=()=>speakText(answer,old);chatMessages.push({role:'ai',text:answer});chatMessages=sanitizeMessages(chatMessages);queueSave()}catch(e){bubble.textContent='Sorry, abhi AI response nahi aa paaya. Please try again.';chatMessages=chatMessages.filter((m,i)=>!(i===chatMessages.length-1&&m.role==='user'));}finally{send.disabled=false;input.focus()}}
async function generateImage(){let prompt=input.value.trim();if(!prompt||!requireAccess())return;if(prompt.length>2000){toast('Image prompt 2000 characters se zyada nahi ho sakta.');return}input.value='';send.disabled=true;const userText=`Create image: ${prompt}`;chatMessages.push({role:'user',text:userText});addMessage('user',userText);const bubble=addMessage('ai','Image bana raha hoon…');try{const res=await fetch('/api/image',{method:'POST',headers:authHeaders(),body:JSON.stringify({prompt,style:'realistic',width:1024,height:1024})});const data=await res.json().catch(()=>({}));if(!res.ok||typeof data.imageUrl!=='string')throw new Error('Image request failed');let imageUrl;try{const u=new URL(data.imageUrl,location.origin);if(!['http:','https:'].includes(u.protocol))throw new Error('bad url');imageUrl=u.href}catch{throw new Error('Invalid image result')}bubble.replaceChildren();const label=document.createElement('div');label.textContent='Done.';const img=document.createElement('img');img.className='image-result';img.src=imageUrl;img.alt='Generated image';img.loading='lazy';const link=document.createElement('a');link.className='image-open';link.href=imageUrl;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Open full size';bubble.append(label,img,link);chatMessages.push({role:'ai',text:`Image generated: ${imageUrl}`});chatMessages=sanitizeMessages(chatMessages);queueSave()}catch(e){bubble.textContent='Image generation failed. Please try again.';chatMessages=chatMessages.filter((m,i)=>!(i===chatMessages.length-1&&m.role==='user'))}finally{send.disabled=false}}
async function speakText(text,button){if(!text)return;if(playingAudio){playingAudio.pause();playingAudio=null;document.querySelectorAll('.speak-btn').forEach(b=>b.classList.remove('active'))}if(button.dataset.playing==='1'){button.dataset.playing='0';return}button.classList.add('active');button.dataset.playing='1';try{const res=await fetch('/api/tts',{method:'POST',headers:authHeaders(),body:JSON.stringify({text:text.slice(0,500)})});if(!res.ok)throw new Error('TTS unavailable');const blob=await res.blob();const url=URL.createObjectURL(blob);const audio=new Audio(url);playingAudio=audio;audio.onended=()=>{button.classList.remove('active');button.dataset.playing='0';URL.revokeObjectURL(url);playingAudio=null};await audio.play()}catch(e){button.classList.remove('active');button.dataset.playing='0';if('speechSynthesis' in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='hi-IN';speechSynthesis.speak(u)}else toast('Voice playback available nahi hai.')}}
function setMode(m){mode=m;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('#modeLabel').textContent=m==='image'?'Image mode':'Chat mode';const modeBtn=document.querySelector('[data-mode="image"]');if(modeBtn){modeBtn.textContent=m==='image'?'◐':'◈';modeBtn.title=m==='image'?'Back to chat':'Image mode'}input.placeholder=m==='image'?'Describe the image you want…':'Ask Munna anything…'}
send.addEventListener('click',()=>mode==='image'?generateImage():sendChat());input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();mode==='image'?generateImage():sendChat()}});input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,160)+'px'});
$('#newChat').onclick=()=>{currentChatId=null;chatMessages=[];renderMessages([]);document.querySelectorAll('.history-item').forEach(b=>b.classList.remove('active'));input.focus()};$('#guest').onclick=guestLogin;$('#authBtn').onclick=()=>session?logout():$('#authModal').classList.add('open');$('#closeAuth').onclick=()=>$('#authModal').classList.remove('open');$('#google2').onclick=google;$('#authSubmit').onclick=()=>$('#authMode').value==='signup'?signUp():signIn();$('#switchAuth').onclick=()=>{const signup=$('#authMode').value!=='signup';$('#authMode').value=signup?'signup':'signin';$('#authSubmit').textContent=signup?'Create account':'Sign in';$('#switchAuth').textContent=signup?'Already have an account? Sign in':'Create a new account'};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(mode==='image'?'chat':b.dataset.mode));document.querySelectorAll('.quick').forEach(b=>b.onclick=()=>{input.value=b.dataset.prompt;input.focus()});
supabase.auth.onAuthStateChange(async(_event,s)=>{session=s;guest=!s&&localStorage.getItem('munna_guest_mode')==='1';setUserUI();if(s){localStorage.removeItem('munna_guest_mode');await loadHistory()}});setMode('chat');loadSession();