const SUPABASE_URL='https://ipnbebwrefxlvoqneaga.supabase.co';
const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwbmJlYndyZWZ4bHZvcW5lYWdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg4ODExOTUsImV4cCI6MjEwNDQ1NzE5NX0.1xMB8DbV__RK8D4PkuYANPARr2IkR_Rsyakh3sU8AAU';
const supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{flowType:'pkce',detectSessionInUrl:true,persistSession:true,autoRefreshToken:true}});
const $=s=>document.querySelector(s); let session=null; let guest=false;
const messages=$('#messages'); const welcome=$('#welcome'); const input=$('#prompt'); const send=$('#send');
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),3200)}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function addMessage(role,text,html=false){welcome.style.display='none';const row=document.createElement('div');row.className=`message ${role}`;const av=document.createElement('div');av.className='avatar';av.textContent=role==='ai'?'M':'You';const bubble=document.createElement('div');bubble.className='bubble';bubble.innerHTML=html?text:escapeHtml(text);if(role==='ai')row.append(av,bubble);else row.append(bubble,av);messages.appendChild(row);messages.parentElement.scrollTop=messages.parentElement.scrollHeight;return bubble}
function setUserUI(){const name=session?.user?.user_metadata?.full_name||session?.user?.email?.split('@')[0]||'Guest';$('#userName').textContent=name;$('#userPlan').textContent=guest?'Guest access':'Signed in';$('#userAvatar').textContent=name.slice(0,1).toUpperCase();$('#authBtn').textContent=guest?'Sign in':'Sign out'}
async function loadSession(){const {data}=await supabase.auth.getSession();session=data.session;guest=!session&&localStorage.getItem('munna_guest_mode')==='1';setUserUI();if(session)localStorage.removeItem('munna_guest_mode')}
function authHeaders(){if(session?.access_token)return {'Authorization':`Bearer ${session.access_token}`,'Content-Type':'application/json'};return {'X-Guest-Access':'true','X-Guest-Id':localStorage.getItem('munna_guest_id')||crypto.randomUUID(),'Content-Type':'application/json'}}
function requireAccess(){if(!session&&!guest){$('#authModal').classList.add('open');return false}return true}
async function signIn(){const email=$('#email').value.trim(),password=$('#password').value;if(!email||!password)return toast('Email aur password enter karo.');const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)return toast(error.message);session=data.session;guest=false;localStorage.removeItem('munna_guest_mode');setUserUI();$('#authModal').classList.remove('open');toast('Welcome back to Munna AI.')}
async function signUp(){const email=$('#email').value.trim(),password=$('#password').value;if(password.length<6)return toast('Password kam se kam 6 characters ka hona chahiye.');const {data,error}=await supabase.auth.signUp({email,password});if(error)return toast(error.message);if(data.session){session=data.session;guest=false;setUserUI();$('#authModal').classList.remove('open');toast('Account ready.')}else toast('Verification email check karo.')}
async function google(){const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin}});if(error)toast(error.message)}
async function logout(){if(session)await supabase.auth.signOut();session=null;guest=false;localStorage.removeItem('munna_guest_mode');setUserUI();toast('Signed out.')}
function guestLogin(){localStorage.setItem('munna_guest_mode','1');localStorage.setItem('munna_guest_id',localStorage.getItem('munna_guest_id')||crypto.randomUUID());guest=true;session=null;setUserUI();$('#authModal').classList.remove('open');toast('Guest mode enabled.')}
async function sendChat(){const text=input.value.trim();if(!text||!requireAccess())return;input.value='';input.style.height='auto';send.disabled=true;addMessage('user',text);const bubble=addMessage('ai','<span class="typing">Munna soch raha hai…</span>',true);try{const history=[...document.querySelectorAll('.message')].slice(-12).map(m=>({role:m.classList.contains('user')?'user':'model',parts:[{text:m.querySelector('.bubble')?.textContent||''}]}));history[history.length-1]={role:'user',parts:[{text}]};const res=await fetch('/api/chat',{method:'POST',headers:authHeaders(),body:JSON.stringify({payload:{contents:history},sse:false})});const data=await res.json();if(!res.ok)throw new Error(data.message||data.error||'Chat request failed');const answer=data?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'Mujhe response nahi mila.';bubble.textContent=answer}catch(e){bubble.textContent='Sorry, abhi AI response nahi aa paaya. '+e.message}finally{send.disabled=false;input.focus()}}
async function generateImage(){const prompt=input.value.trim();if(!prompt||!requireAccess())return;input.value='';send.disabled=true;addMessage('user',`Create image: ${prompt}`);const bubble=addMessage('ai','Image bana raha hoon…');try{const res=await fetch('/api/image',{method:'POST',headers:authHeaders(),body:JSON.stringify({prompt,style:'realistic',width:1024,height:1024})});const data=await res.json();if(!res.ok)throw new Error(data.message||data.error||'Image request failed');bubble.innerHTML=`<div>Done.</div><img class="image-result" src="${escapeHtml(data.imageUrl)}" alt="Generated image">`}catch(e){bubble.textContent='Image generation failed: '+e.message}finally{send.disabled=false}}
let mode='chat';function setMode(m){mode=m;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('#modeLabel').textContent=m==='image'?'Image mode':'Chat mode'}
send.addEventListener('click',()=>mode==='image'?generateImage():sendChat());input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();mode==='image'?generateImage():sendChat()}});input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,160)+'px'});
$('#newChat').onclick=()=>{messages.innerHTML='';welcome.style.display='block';input.focus()};$('#guest').onclick=guestLogin;$('#authBtn').onclick=()=>session?logout():$('#authModal').classList.add('open');$('#closeAuth').onclick=()=>$('#authModal').classList.remove('open');$('#google2').onclick=google;$('#authSubmit').onclick=()=>$('#authMode').value==='signup'?signUp():signIn();$('#switchAuth').onclick=()=>{const signup=$('#authMode').value!=='signup';$('#authMode').value=signup?'signup':'signin';$('#authSubmit').textContent=signup?'Create account':'Sign in';$('#switchAuth').textContent=signup?'Already have an account? Sign in':'Create a new account'};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('.quick').forEach(b=>b.onclick=()=>{input.value=b.dataset.prompt;input.focus()});
supabase.auth.onAuthStateChange((_event,s)=>{session=s;guest=!s&&localStorage.getItem('munna_guest_mode')==='1';setUserUI()});loadSession();