const SUPABASE_URL='https://ipnbebwrefxlvoqneaga.supabase.co';
const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwbmJlYndyZWZ4bHZvcW5lYWdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg4ODExOTUsImV4cCI6MjEwNDQ1NzE5NX0.1xMB8DbV__RK8D4PkuYANPARr2IkR_Rsyakh3sU8AAU';
const supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{flowType:'pkce',detectSessionInUrl:true,persistSession:true,autoRefreshToken:true}});
const $=s=>document.querySelector(s);let session=null,guest=false,mode='chat',currentChatId=null,chatMessages=[],playingAudio=null;
const messages=$('#messages'),welcome=$('#welcome'),input=$('#prompt'),send=$('#send'),historyList=$('.history');
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),3200)}
function escapeHtml(v){return String(v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]))}
function addMessage(role,text){welcome.style.display='none';const row=document.createElement('div');row.className=`message ${role}`;const av=document.createElement('div');av.className='avatar';av.textContent=role==='ai'?'M':'You';const bubble=document.createElement('div');bubble.className='bubble';bubble.textContent=text;if(role==='ai'){const wrap=document.createElement('div');wrap.className='ai-content';wrap.appendChild(bubble);const speak=document.createElement('button');speak.className='speak-btn';speak.title='Read aloud';speak.setAttribute('aria-label','Read aloud');speak.textContent='🔊';speak.onclick=()=>speakText(text,speak);wrap.appendChild(speak);row.append(av,wrap)}else row.append(bubble,av);messages.appendChild(row);messages.parentElement.scrollTop=messages.parentElement.scrollHeight;return bubble}
function renderMessages(items){messages.innerHTML='';welcome.style.display=items.length?'none':'block';for(const m of items)addMessage(m.role,m.text)}
function setUserUI(){const name=session?.user?.user_metadata?.full_name||session?.user?.email?.split('@')[0]||'Guest';$('#userName').textContent=name;$('#userPlan').textContent=guest?'Guest access':session?'Cloud sync enabled':'Sign in to sync';$('#userAvatar').textContent=name.slice(0,1).toUpperCase();$('#authBtn').textContent=guest||session?'Sign out':'Sign in'}
async function loadSession(){const {data}=await supabase.auth.getSession();session=data.session;guest=!session&&localStorage.getItem('munna_guest_mode')==='1';setUserUI();if(session){localStorage.removeItem('munna_guest_mode');await loadHistory()}}
function authHeaders(){if(session?.access_token)return {'Authorization':`Bearer ${session.access_token}`,'Content-Type':'application/json'};return {'X-Guest-Access':'true','X-Guest-Id':localStorage.getItem('munna_guest_id')||crypto.randomUUID(),'Content-Type':'application/json'}}
function requireAccess(){if(!session&&!guest){$('#authModal').classList.add('open');return false}return true}
async function signIn(){const email=$('#email').value.trim(),password=$('#password').value;if(!email||!password)return toast('Email aur password enter karo.');const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)return toast(error.message);session=data.session;guest=false;localStorage.removeItem('munna_guest_mode');setUserUI();$('#authModal').classList.remove('open');await loadHistory();toast('Welcome back to Munna AI.')}
async function signUp(){const email=$('#email').value.trim(),password=$('#password').value;if(password.length<6)return toast('Password kam se kam 6 characters ka hona chahiye.');const {data,error}=await supabase.auth.signUp({email,password});if(error)return toast(error.message);if(data.session){session=data.session;guest=false;setUserUI();$('#authModal').classList.remove('open');await loadHistory();toast('Account ready.')}else toast('Verification email check karo.')}
async function google(){const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin}});if(error)toast(error.message)}
async function logout(){if(session)await supabase.auth.signOut();session=null;guest=false;currentChatId=null;chatMessages=[];localStorage.removeItem('munna_guest_mode');setUserUI();renderMessages([]);renderHistory([]);toast('Signed out.')}
function guestLogin(){localStorage.setItem('munna_guest_mode','1');localStorage.setItem('munna_guest_id',localStorage.getItem('munna_guest_id')||crypto.randomUUID());guest=true;session=null;currentChatId=null;chatMessages=[];setUserUI();renderMessages([]);$('#authModal').classList.remove('open');toast('Guest mode enabled.')}
async function saveChat(){if(!session||!chatMessages.length)return;const title=(chatMessages.find(m=>m.role==='user')?.text||'New conversation').slice(0,70);if(!currentChatId)currentChatId=crypto.randomUUID();const {error}=await supabase.from('chat_sessions').upsert({id:currentChatId,user_id:session.user.id,title,messages:chatMessages,updated_at:new Date().toISOString()});if(error)console.warn('Chat sync failed:',error.message);else await loadHistory(false)}
async function loadHistory(selectLatest=false){if(!session){renderHistory([]);return}const {data,error}=await supabase.from('chat_sessions').select('id,title,messages,updated_at').order('updated_at',{ascending:false}).limit(30);if(error){console.warn('History load failed:',error.message);renderHistory([]);return}renderHistory(data||[]);if(selectLatest&&data?.[0])openChat(data[0])}
function renderHistory(items){historyList.innerHTML='';if(!items.length){const b=document.createElement('button');b.className='history-item active';b.textContent='✨ Welcome to Munna';historyList.appendChild(b);return}items.forEach(item=>{const b=document.createElement('button');b.className='history-item';b.textContent=item.title||'Untitled conversation';b.title=item.title||'';b.onclick=()=>openChat(item);historyList.appendChild(b)})}
function openChat(item){currentChatId=item.id;chatMessages=Array.isArray(item.messages)?item.messages:[];renderMessages(chatMessages);document.querySelectorAll('.history-item').forEach(b=>b.classList.toggle('active',b.textContent===(item.title||'Untitled conversation')));input.focus()}
async function sendChat(){const text=input.value.trim();if(!text||!requireAccess())return;input.value='';input.style.height='auto';send.disabled=true;if(!currentChatId)currentChatId=crypto.randomUUID();chatMessages.push({role:'user',text});addMessage('user',text);const bubble=addMessage('ai','Munna soch raha hai…');try{const history=chatMessages.slice(-12).map(m=>({role:m.role==='user'?'user':'model',parts:[{text:m.text}]}));const res=await fetch('/api/chat',{method:'POST',headers:authHeaders(),body:JSON.stringify({payload:{contents:history},sse:false})});const data=await res.json();if(!res.ok)throw new Error(data.message||data.error||'Chat request failed');const answer=data?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'Mujhe response nahi mila.';bubble.textContent=answer;const row=bubble.closest('.message');const old=row?.querySelector('.speak-btn');if(old)old.onclick=()=>speakText(answer,old);chatMessages.push({role:'ai',text:answer});await saveChat()}catch(e){bubble.textContent='Sorry, abhi AI response nahi aa paaya. '+e.message;chatMessages.pop()}finally{send.disabled=false;input.focus()}}
async function generateImage(){const prompt=input.value.trim();if(!prompt||!requireAccess())return;input.value='';send.disabled=true;const userText=`Create image: ${prompt}`;chatMessages.push({role:'user',text:userText});addMessage('user',userText);const bubble=addMessage('ai','Image bana raha hoon…');try{const res=await fetch('/api/image',{method:'POST',headers:authHeaders(),body:JSON.stringify({prompt,style:'realistic',width:1024,height:1024})});const data=await res.json();if(!res.ok)throw new Error(data.message||data.error||'Image request failed');bubble.innerHTML=`<div>Done.</div><img class="image-result" src="${escapeHtml(data.imageUrl)}" alt="Generated image">`;chatMessages.push({role:'ai',text:`Image generated: ${data.imageUrl}`});await saveChat()}catch(e){bubble.textContent='Image generation failed: '+e.message;chatMessages.pop()}finally{send.disabled=false}}
async function speakText(text,button){if(!text)return;if(playingAudio){playingAudio.pause();playingAudio=null;document.querySelectorAll('.speak-btn').forEach(b=>b.classList.remove('active'));}if(button.dataset.playing==='1'){button.dataset.playing='0';return}button.classList.add('active');button.dataset.playing='1';try{const res=await fetch('/api/tts',{method:'POST',headers:authHeaders(),body:JSON.stringify({text})});if(!res.ok)throw new Error('TTS unavailable');const blob=await res.blob();const url=URL.createObjectURL(blob);const audio=new Audio(url);playingAudio=audio;audio.onended=()=>{button.classList.remove('active');button.dataset.playing='0';URL.revokeObjectURL(url);playingAudio=null};await audio.play()}catch(e){button.classList.remove('active');button.dataset.playing='0';if('speechSynthesis' in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='hi-IN';speechSynthesis.speak(u)}else toast('Voice playback available nahi hai.') }}
function setMode(m){mode=m;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('#modeLabel').textContent=m==='image'?'Image mode':'Chat mode';const modeBtn=document.querySelector('[data-mode="image"]');if(modeBtn){modeBtn.textContent=m==='image'?'◐':'◈';modeBtn.title=m==='image'?'Back to chat':'Image mode'}input.placeholder=m==='image'?'Describe the image you want…':'Ask Munna anything…'}
send.addEventListener('click',()=>mode==='image'?generateImage():sendChat());input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();mode==='image'?generateImage():sendChat()}});input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,160)+'px'});
$('#newChat').onclick=()=>{currentChatId=null;chatMessages=[];renderMessages([]);document.querySelectorAll('.history-item').forEach(b=>b.classList.remove('active'));input.focus()};$('#guest').onclick=guestLogin;$('#authBtn').onclick=()=>session?logout():$('#authModal').classList.add('open');$('#closeAuth').onclick=()=>$('#authModal').classList.remove('open');$('#google2').onclick=google;$('#authSubmit').onclick=()=>$('#authMode').value==='signup'?signUp():signIn();$('#switchAuth').onclick=()=>{const signup=$('#authMode').value!=='signup';$('#authMode').value=signup?'signup':'signin';$('#authSubmit').textContent=signup?'Create account':'Sign in';$('#switchAuth').textContent=signup?'Already have an account? Sign in':'Create a new account'};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('.quick').forEach(b=>b.onclick=()=>{input.value=b.dataset.prompt;input.focus()});
supabase.auth.onAuthStateChange(async(_event,s)=>{session=s;guest=!s&&localStorage.getItem('munna_guest_mode')==='1';setUserUI();if(s)await loadHistory();});setMode('chat');loadSession();