(() => {
  const $ = s => document.querySelector(s);
  const toast = m => window.toast ? window.toast(m) : console.log(m);
  const css = `.billing-modal{display:none;position:fixed;inset:0;background:rgba(4,7,11,.82);backdrop-filter:blur(12px);z-index:10000;align-items:center;justify-content:center;padding:20px}.billing-modal.open{display:flex}.billing-card{width:min(900px,96vw);max-height:90vh;overflow:auto;background:linear-gradient(180deg,#101722,#090d13);border:1px solid #293446;border-radius:26px;padding:28px;box-shadow:0 30px 90px rgba(0,0,0,.55)}.billing-head{display:flex;justify-content:space-between;gap:20px;margin-bottom:20px}.billing-head h2{font-size:30px;margin:8px 0}.billing-head p{color:#7f8a9c;margin:0;font-size:13px}.billing-plan-badge,.billing-chip{display:inline-flex;padding:8px 11px;border:1px solid #313c4d;background:#111823;border-radius:999px;color:#c4b5fd;font-size:11px}.billing-plans{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.plan-card{position:relative;border:1px solid #273241;background:#0c121a;border-radius:18px;padding:20px;display:flex;flex-direction:column;min-height:280px}.plan-card.featured{border-color:#6d5dfc;box-shadow:0 0 0 1px rgba(109,93,252,.15),0 18px 50px rgba(109,93,252,.08)}.popular{position:absolute;right:14px;top:14px;font-size:9px;color:#c4b5fd;background:#211b3b;border:1px solid #5143a5;padding:5px 7px;border-radius:999px}.plan-card h3{margin:0 0 8px}.plan-price{font-size:32px;font-weight:700;margin:5px 0}.plan-price small{color:#697588;font-size:11px}.plan-desc{font-size:11px;color:#7f8a9c}.plan-features{list-style:none;padding:0;margin:16px 0;display:grid;gap:8px;color:#aeb8c7;font-size:11px}.plan-features li:before{content:'✓';color:#4ade80;margin-right:7px}.plan-btn{margin-top:auto;width:100%;padding:10px;border-radius:11px;border:1px solid #303b4c;background:#141b25;color:#fff;font-weight:700;cursor:pointer}.featured .plan-btn{background:linear-gradient(135deg,#6d5dfc,#8b5cf6);border-color:transparent}.billing-current{margin:0 0 18px}.billing-note{margin-top:16px;color:#596679;font-size:10px;text-align:center}@media(max-width:820px){.billing-plans{grid-template-columns:1fr}.billing-card{padding:20px}.billing-head{flex-direction:column}}`;
  const style = document.createElement('style'); style.textContent = css; document.head.appendChild(style);
  const btn = document.createElement('button'); btn.id='billingBtn'; btn.className='settings-link'; btn.textContent='👑 Upgrade / Plans';
  const footer = document.querySelector('.side-footer'); if (footer) footer.insertBefore(btn, footer.firstChild);
  const modal = document.createElement('div'); modal.id='billingModal'; modal.className='billing-modal'; modal.innerHTML=`<div class="billing-card"><button class="close" id="closeBilling">×</button><div class="billing-head"><div><span class="eyebrow">Munna AI Membership</span><h2>Apna Munna upgrade karo.</h2><p>More AI power, higher limits and premium workspace features.</p></div><div class="billing-plan-badge" id="billingPlanBadge">Current: Free</div></div><div class="billing-current" id="billingCurrent"></div><div class="billing-plans"><article class="plan-card"><h3>Free</h3><div class="plan-price">₹0 <small>/ forever</small></div><div class="plan-desc">Basic AI access.</div><ul class="plan-features"><li>10 AI messages/day</li><li>Basic chat</li><li>Guest-friendly access</li></ul><button class="plan-btn" disabled>Current plan</button></article><article class="plan-card featured"><span class="popular">Most popular</span><h3>Pro</h3><div class="plan-price">₹299 <small>/ 30 days</small></div><div class="plan-desc">Creators, students aur builders ke liye.</div><ul class="plan-features"><li>1,000 AI messages/day</li><li>Image + voice features</li><li>Priority limits</li><li>Premium support</li></ul><button class="plan-btn buy-plan" data-plan="pro">Upgrade to Pro</button></article><article class="plan-card"><h3>Business</h3><div class="plan-price">₹799 <small>/ 30 days</small></div><div class="plan-desc">Teams aur heavy AI usage ke liye.</div><ul class="plan-features"><li>5,000 AI messages/day</li><li>Higher workspace limits</li><li>Team-ready billing layer</li><li>Priority support</li></ul><button class="plan-btn buy-plan" data-plan="business">Get Business</button></article></div><div class="billing-note">Payments are securely processed by Razorpay. Subscription activates only after server-side verification.</div></div>`;
  document.body.appendChild(modal);
  const loadRazorpay = () => new Promise((resolve,reject)=>{ if(window.Razorpay)return resolve(); const s=document.createElement('script'); s.src='https://checkout.razorpay.com/v1/checkout.js'; s.onload=resolve; s.onerror=reject; document.head.appendChild(s); });
  async function token(){try{const client=window.supabaseClient||window.supabase;const {data}=await client?.auth?.getSession?.();return data?.session?.access_token||'';}catch{return ''}}
  async function state(){const t=await token();if(!t)return{plan:'guest',configured:false};const r=await fetch('/api/billing',{headers:{Authorization:`Bearer ${t}`}});return r.ok?r.json():{plan:'free',configured:false}}
  async function refresh(){const s=await state();const label=s.plan==='business'?'Business':s.plan==='pro'?'Pro':s.plan==='guest'?'Guest':'Free';$('#billingPlanBadge').textContent=`Current: ${label}`;$('#billingCurrent').innerHTML=`<div class="billing-chip">Current access: <strong>${label}</strong>${s.expires_at?' · active until '+new Date(s.expires_at).toLocaleDateString():''}</div>`;document.querySelectorAll('.buy-plan').forEach(b=>{b.disabled=s.plan===b.dataset.plan;b.textContent=b.disabled?'Current plan':b.dataset.plan==='pro'?'Upgrade to Pro':'Get Business'});return s}
  async function buy(plan){const t=await token();if(!t){toast('Upgrade ke liye pehle sign in karo.');$('#authModal')?.classList.add('open');return}const s=await state();if(!s.configured){toast('Billing server par configure nahi hai. Razorpay keys add karo.');return}const r=await fetch('/api/billing',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({action:'create-order',plan})});const d=await r.json().catch(()=>({}));if(!r.ok){toast(d.message||'Payment order create nahi hua.');return}try{await loadRazorpay()}catch{toast('Razorpay checkout load nahi hua.');return}new Razorpay({key:d.key_id,amount:d.amount,currency:d.currency,name:'Munna AI',description:d.name,order_id:d.order_id,handler:async response=>{const vr=await fetch('/api/billing',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({action:'verify',plan,order_id:response.razorpay_order_id,payment_id:response.razorpay_payment_id,signature:response.razorpay_signature})});const out=await vr.json().catch(()=>({}));if(!vr.ok||!out.ok){toast(out.message||'Payment verify nahi hua.');return}toast(`🔥 ${plan==='pro'?'Pro':'Business'} plan activate ho gaya!`);refresh()},modal:{ondismiss:()=>toast('Payment window band kar di gayi.')},theme:{color:'#6d5dfc'}}).open()}
  btn.addEventListener('click',()=>{modal.classList.add('open');refresh()});$('#closeBilling').addEventListener('click',()=>modal.classList.remove('open'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});document.querySelectorAll('.buy-plan').forEach(b=>b.addEventListener('click',()=>buy(b.dataset.plan)));window.openBilling=()=>{modal.classList.add('open');refresh()};
})();
